name: Weather Alerts Poller

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows you to manually trigger it

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run Weather Script
        env:
          OUTLOOK_WEBHOOK: ${{ secrets.OUTLOOK_WEBHOOK }}
          MCD_WEBHOOK: ${{ secrets.MCD_WEBHOOK }}
          SVR_WEBHOOK: ${{ secrets.SVR_WEBHOOK }}
          TORNADO_WEBHOOK: ${{ secrets.TORNADO_WEBHOOK }}
          TROPICAL_WEBHOOK: ${{ secrets.TROPICAL_WEBHOOK }}
          FLOOD_WEBHOOK: ${{ secrets.FLOOD_WEBHOOK }}
          HURRICANE_WEBHOOK: ${{ secrets.HURRICANE_WEBHOOK }}
          WINTER_WEBHOOK: ${{ secrets.WINTER_WEBHOOK }}
        run: python main.py
