name: Weather Alerts Poller

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows you to manually trigger it

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run Weather Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python3 main.py
